:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0
:revealjs_slideNumber: true
:source-highlighter: highlightjs
:icons: font
:allow-uri-read:
:imagesdir: /images
:stylesheet: adoc-golo.css
:numbered:
:toc: left
:toc-title: Sumário
:toclevels: 5

ifdef::env-github[]
//Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub

:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

:chapter-label:
:description: Elaboração de material didático multimídia com AsciiDoc, git e GitHub
:listing-caption: Listagem
:figure-caption: Figura

= Elaboração de material didático multimídia com AsciiDoc, git e GitHub

== Instalação das ferramentas

Execute o script link:ferramentas.sh[ferramentas.sh] em um terminal com sistema Ubuntu ou qualquer derivado de Debian: 

[source, bash]
----
sh ferramentas.sh
----

Se sua distribuição for antiga ou não for 64 bits, pode ser que a instalação do Visual Studio code não funcione. Se ocorrer erro, pode editar o script acima, apagar as linhas 3 até 7 e executar novamente. Em seguida, baixe o Visual Studio Code manualmente em http://code.visualstudio.com

Crie uma conta no GitHub em https://github.com/signup. O nome de usuário se torna o link para sua conta pública, como http://github.com/manoelcampos. Por isso, escolha o nome apropriadamente.

Qualquer dúvida, podem entrar em contato diretamente comigo.
Para qualquer alteração em um projeto que você desejar enviar para o GitHub a partir da sua máquina, você precisará informar nome de usuário e senha. Isso se tornará um processo bastante chato e que toma tempo. Para evitar isso, na nossa máquina pessoal, podemos configurar a autenticação por meio de um par de chaves pública/privada. Para isto, siga o tutorial disponível https://youtu.be/Qp0lDxgoQE0[aqui].

ifdef::backend-pdf[]
include::comandos/README.adoc[]
endif::[]

ifndef::backend-pdf[]
== Comandos AsciiDoc

link:comandos[Um resumo dos comandos AsciiDoc está disponível aqui.]
endif::[]


== Referências

- https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Official Writer’s Guide]
- https://asciidoctor.org/docs/[Toda a Documentação oficial do AsciiDoc]
- https://github.com/darshandsoni/asciidoctor-skins[Temas em CSS]